version: "3.9"
services:
  chat-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      
  chat-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  chat-db:
    image: postgres
    environment:
      POSTGRES_USER: chatUser
      POSTGRES_PASSWORD: chatPassword
      POSTGRES_DB: chatDatabase
    ports:
      - "5432:5432"